[package]
name = "perspective"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[target.wasm32-wasi]
rustflags = ["-Z", "wasi-exec-model=reactor"]

[profile.release]
# lto = "thin"

[dependencies]
cxx = "1.0.109"
link-cplusplus = { version = "1.0.9", features = ["libc++"] }
wasm-bindgen = "0.2.87"

[build-dependencies]
cmake = "0.1.50"
cxx-build = "1.0.109"
